trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $url = 'https://www.netsparkercloud.com/api/1.0/websites/list/new'
      $headers = @{'Content-Type' = 'application/json'; 'Accept' = 'application/json'; 'Authorization' = 'Basic YmRiM2U2ZTQyZThkNGNkNTNmZjhhZTU4MDFmZWMyMDg6ZklUKzZIS01PM29pbzBRYklVWWJpM0dMcTNEVEhQdjQvRnJUWnQ0Mzh6WT0=' }
      
      $data = @'
      {
          "AgentMode": "Cloud",
          "RootUrl": "http://www.example2.com",
          "Groups": [],
          "LicenseType": "Subscription",
          "Name": "test4",
          "Description": "",
          "Tags": [
              "a"
          ]
      }
      '@
      
      $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Post -Body $data
      
      if ($response.StatusCode -eq 201) {
          Write-Host "New target added successfully."
      } else {
          Write-Host "Failed to add the new target. Status code: $($response.StatusCode)"
          Write-Host "Response body: $($response.Content)"
      }
- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '2'
    scanWebSites: '7ce8c8ea-cbcc-46bd-2e18-b01a0266716d'
    scanWebSitesProfile: 'eae4fab5-2910-4567-2772-b01a02708950'