trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{
          'Content-Type' = 'application/json'
          'Accept' = 'application/json'
          'Authorization' = 'Basic YmRiM2U2ZTQyZThkNGNkNTNmZjhhZTU4MDFmZWMyMDg6ZklUKzZIS01PM29pbzBRYklVWWJpM0dMcTNEVEhQdjQvRnJUWnQ0Mzh6WT0='
      }
      
      $body = @{
          "AgentMode" = "Cloud"
          "RootUrl" = "http://example9.com"
          "LicenseType" = "Subscription"
          "Name" = "Blue Fizz 55"
          "Description" = "Sample Description"
          "Tags" = @("TagWithNoValue", "TagWithValue:Value")
      }
      
      $jsonBody = $body | ConvertTo-Json
      
      $url = 'https://www.netsparkercloud.com/api/1.0/websites/new'
      
      $response = Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $jsonBody
      
      # Display the response
      Write-Output $response
- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '2'
    scanWebSites: '7ce8c8ea-cbcc-46bd-2e18-b01a0266716d'
    scanWebSitesProfile: 'eae4fab5-2910-4567-2772-b01a02708950'