trigger:

- master

pool:
  vmImage: 'windows-latest'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      
$uri = 'https://www.netsparkercloud.com/api/1.0/scanprofiles/update'

    $headers = @{ 
    'Content-Type'  = 'application/json'
    'Accept'        = 'application/json'
    'Authorization' = 'Basic YmRiM2U2ZTQyZThkNGNkNTNmZjhhZTU4MDFmZWMyMDg6ZklUKzZIS01PM29pbzBRYklVWWJpM0dMcTNEVEhQdjQvRnJUWnQ0Mzh6WT0='
}

$body = @{
    "AgentGroupId"                      = None
    "AgentId"                           = None
    "CreateType"                        = "Website"
    "IsPrimary"                         = false
    "IsShared"                          = true
    "IsTimeWindowEnabled"               = false
    "PolicyId"                          = "2efccb38-7537-4a76-0006-ae520217285b"
    "ProfileId"                         = "30e839fc-8432-48f7-5e04-afe703378a30"
    "ProfileName"                       = "tron babe 2"
    "ReportPolicyId"                    = "c96bd18b-0936-489e-5125-af2a02cbd573"
    "TargetUri"                         = "http://testaspnet.vulnweb.com/"
    "UserId"                            = "bdb3e6e4-2e8d-4cd5-3ff8-ae5801fec208"
    "AdditionalWebsites"                = @()
    "BasicAuthenticationApiModel"       = @{
        "Credentials"                   = $null
        "IsEnabled"                     = false
        "NoChallenge"                   = false
    }
    "ClientCertificateAuthenticationSetting" = $null
    "Cookies"                           = $null
    "CrawlAndAttack"                    = true
    "EnableHeuristicChecksInCustomUrlRewrite" = true
    "ExcludedLinks"                     = @(
        {
            "RegexPattern"              = "gtm\.js"
        },
        {
            "RegexPattern"              = "WebResource\.axd"
        },
        {
            "RegexPattern"              = "ScriptResource\.axd"
        },

    )
    "ExcludedUsageTrackers"             = @()
    "DisallowedHttpMethods"             = @()
    "ExcludeLinks"                      = {str(scan_details['ExcludeLinks']).lower()}
    "ExcludeAuthenticationPages"        = {str(scan_details['ExcludeAuthenticationPages']).lower()}
    "FindAndFollowNewLinks"             = {str(scan_details['FindAndFollowNewLinks']).lower()}
    "FormAuthenticationSettingModel"    = @{{
        "Integrations"                  = @{{}}
        "CustomScripts"                 = @()
        "InteractiveLoginRequired"      = {str(scan_details['FormAuthenticationSettingModel']['InteractiveLoginRequired']).lower()}
        "DefaultPersonaValidation"      = $null
        "DetectBearerToken"             = {str(scan_details['FormAuthenticationSettingModel']['DetectBearerToken']).lower()}
        "DisableLogoutDetection"        = {str(scan_details['FormAuthenticationSettingModel']['DisableLogoutDetection']).lower()}
        "IsEnabled"                     = {str(scan_details['FormAuthenticationSettingModel']['IsEnabled']).lower()}
        "IsNotVerified"                 = {str(scan_details['FormAuthenticationSettingModel']['IsNotVerified']).lower()}
        "LoginFormUrl"                  = $null
        "LoginRequiredUrl"              = $null
        "LogoutKeywordPatterns"         = $null
        "LogoutKeywordPatternsValue"    = $null
        "LogoutRedirectPattern"         = $null
        "OverrideTargetUrl"             = {str(scan_details['FormAuthenticationSettingModel']['OverrideTargetUrl']).lower()}
        "Personas"                      = @()
        "PersonasValidation"            = $null
        "AuthorizationTokenRules"       = @()
    }}
    "HeaderAuthentication"             = @{{
        "Headers"                       = @()
        "IsEnabled"                     = {str(scan_details['HeaderAuthentication']['IsEnabled']).lower()}
    }}
    "SharkSetting"                      = $null
    "AuthenticationProfileOption"      = "{scan_details['AuthenticationProfileOption']}"
    "AuthenticationProfileId"          = $null
    "ImportedLinks"                    = @()
    "ImportedFiles"                    = @()
    "IsMaxScanDurationEnabled"         = {str(scan_details['IsMaxScanDurationEnabled']).lower()}
    "MaxDynamicSignatures"             = {scan_details['MaxDynamicSignatures']}
    "MaxScanDuration"                  = {scan_details['MaxScanDuration']}
    "Scope"                            = "{scan_details['Scope']}"
    "SubPathMaxDynamicSignatures"      = {scan_details['SubPathMaxDynamicSignatures']}
    "TimeWindow"                       = @{{
        "Items"                        = @(
            {
                "Day"                  = "Monday"
                "From"                 = "09:00"
                "ScanningAllowed"      = true
                "To"                   = "18:00"
            },
            {
                "Day"                  = "Tuesday"
                "From"                 = "09:00"
                "ScanningAllowed"      = true
                "To"                   = "18:00"
            },
            {
                "Day"                  = "Wednesday"
                "From"                 = "09:00"
                "ScanningAllowed"      = true
                "To"                   = "18:00"
            },
            {
                "Day"                  = "Thursday"
                "From"                 = "09:00"
                "ScanningAllowed"      = true
                "To"                   = "18:00"
            },
            {
                "Day"                  = "Friday"
                "From"                 = "09:00"
                "ScanningAllowed"      = true
                "To"                   = "18:00"
            },
            {
                "Day"                  = "Saturday"
                "From"                 = "09:00"
                "ScanningAllowed"      = true
                "To"                   = "18:00"
            },
            {
                "Day"                  = "Sunday"
                "From"                 = "09:00"
                "ScanningAllowed"      = true
                "To"                   = "18:00"
            },

        )
    }}
    "UrlRewriteAnalyzableExtensions"    = "{scan_details['UrlRewriteAnalyzableExtensions']}"
    "UrlRewriteBlockSeparators"         = "{scan_details['UrlRewriteBlockSeparators']}"
    "UrlRewriteMode"                    = "{scan_details['UrlRewriteMode']}"
    "UrlRewriteRules"                   = @()
    "PreRequestScriptSetting"           = @{{
        "IsEnabled"                     = {str(scan_details['PreRequestScriptSetting']['IsEnabled']).lower()}
        "Content"                       = $null
    }}
    "DoNotDifferentiateProtocols"       = {str(scan_details['DoNotDifferentiateProtocols']).lower()}
    "UrlRewriteExcludedLinks"           = @()
    "OAuth2SettingModel"                = $null
    "EnablePciScanTask"                 = {str(scan_details['EnablePciScanTask']).lower()}
    "BusinessLogicRecorderSetting"      = @{{
        "SequenceModelList"            = $null
    }}
    "Tags"                              = {json.dumps(scan_details['Tags'])}
    "Comments"                          = test purpose
}}

Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body ($body | ConvertTo-Json -Depth 10)

- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '2'
    scanWebSites: '2e1498ff-ad9a-4569-c4e4-ae8301b8e800'
    scanWebSitesProfile: '7b8692de-d855-4d7d-dc24-af2a02ccb87d'
    buildFail: true
    severity: 'Critical,High,Medium'
    stopScan: true
