trigger:

- master

pool:
  vmImage: 'windows-latest'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $Headers = @{
          'Content-Type' = 'application/json'
          'Accept' = 'application/json'
          'Authorization' = 'Basic YmRiM2U2ZTQyZThkNGNkNTNmZjhhZTU4MDFmZWMyMDg6ZklUKzZIS01PM29pbzBRYklVWWJpM0dMcTNEVEhQdjQvRnJUWnQ0Mzh6WT0='
      }
      
      $Body = @{
          "DefaultProtocol" = "Http"
          "AgentMode" = "Internal"
          "RootUrl" = "http://graphql.testinvicti.com/"
          "Groups" = @()
          "LicenseType" = "Subscription"
          "Name" = "http://graphql.testinvicti.com/"
          "Description" = "string"
          "Tags" = @("test", "asml")
      }
      
      $Url = 'https://www.netsparkercloud.com/api/1.0/websites/update'
      
      Invoke-RestMethod -Method Post -Uri $Url -Headers $Headers -Body ($Body | ConvertTo-Json)
- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '2'
    scanWebSites: '2e1498ff-ad9a-4569-c4e4-ae8301b8e800'
    scanWebSitesProfile: '7b8692de-d855-4d7d-dc24-af2a02ccb87d'
    buildFail: true
    severity: 'Critical,High,Medium'
    stopScan: true
