trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:

- checkout: self

- task: CreateDASTTarget@1
  name: createTargetStep
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetAddress: 'http://vulnapi.testinvicti.com/'
    criticality: '30'

- task: ConfigureDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetId: '$(createTargetStep.DASTTargetId)'
    limitCrawlerScope: true
    scanSpeed: 'fast'
    importFilePath: 'openapi-swagger_basicauthentication.yaml'
    authenticationEnabled: false

- task: StartDASTScan@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    criticalThreshold: '0'
    highThreshold: '3'
    targetId: '$(createTargetStep.DASTTargetId)'
    profileId: '11111111-1111-1111-1111-111111111111'
    scheduleDisable: true