trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
- task: CreateDASTTarget@1
  name: createTask
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetAddress: 'http://example.com/haydaaa5'
    criticality: '30'

- task: ConfigureDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetId: '$(createTask.DASTTargetId)'
    limitCrawlerScope: true
    scanSpeed: 'fast'
    authenticationEnabled: true
    authUsername: 'test'
    authPassword: 'test'
    authUrl: 'http://example.com'

- task: StartDASTScan@1
  inputs:
    criticalThreshold: '2'
    highThreshold: '2'
    abortScanOnFindings: true
    targetId: '$(createTask.DASTTargetId)'
    scheduleDisable: true