trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
- task: CreateDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    apiKey: $(DAST_API_KEY)
    targetAddress: 'http://example.com/final2'
    description: 'DAST created from Azure DevOps 2'
    criticality: '30'

- task: ConfigureDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetId: 
    limitCrawlerScope: true
    scanSpeed: 'medium'
    authenticationEnabled: true
    authUsername: 'test'
    authPassword: 'test'
    authUrl: 'http://example.com/final2'

- task: StartDASTScan@1
  inputs:
    criticalThreshold: '2'
    highThreshold: '2'
    abortScanOnFindings: true
    targetId: 
    scheduleDisable: true