trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:

- checkout: self

- task: CreateDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetAddress: 'http://example.com/ohyeahletsgoparty'
    criticality: '30'

- task: ConfigureDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetId: '$(createTask.DASTTargetId)'
    limitCrawlerScope: true
    scanSpeed: 'fast'
    importFilePath: 'openapi-swagger_basicauthentication.yaml'
    authenticationEnabled: false

- task: StartDASTScan@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    criticalThreshold: '0'
    highThreshold: '0'
    targetId: '$(createTask.DASTTargetId)'
    scheduleDisable: true
