trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:

- checkout: self

- script: |
    echo "Current working directory:"
    echo $(Build.SourcesDirectory)
    echo "Listing files recursively:"
    dir "$(Build.SourcesDirectory)" /s
  displayName: 'Debug: List files in sources directory'


- task: CreateDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetAddress: 'http://rest.testinvicti.com/basic_authentication'
    criticality: '30'

- task: ConfigureDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetId: '$(createTask.DASTTargetId)'
    limitCrawlerScope: true
    scanSpeed: 'fast'
    importFilePath: 'openapi-swagger_basicauthentication.yaml'
    authenticationEnabled: false

- task: StartDASTScan@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    criticalThreshold: '2'
    highThreshold: '0'
    targetId: '$(createTask.DASTTargetId)'
    scheduleDisable: true

