trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:

- checkout: self

- task: netsparker-cloud@1
  inputs:
    apiConnection: 'Project Team A DAST Connection'
    scanTypes: '1'
    scanWebSites: '7ce8c8ea-cbcc-46bd-2e18-b01a0266716d'