trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
- task: CreateDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetAddress: 'http://rest.testinvicti.com/basic_authentication'
    criticality: '30'

- task: ConfigureDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetId: '$(createTask.DASTTargetId)'
    limitCrawlerScope: true
    scanSpeed: 'fast'
    importFilePath: 'import_files/openapi-swagger_basicauthentication.yaml'
    authenticationEnabled: false

- task: StartDASTScan@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    criticalThreshold: '2'
    highThreshold: '0'
    targetId: '$(createTask.DASTTargetId)'
    scheduleDisable: true