trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
- task: CreateDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    apiKey: '1b5abcca1ebbd4a108e04a0891832b21a9d39f530a698f876a5ab6666f3e20831'
    targetAddress: 'http://example.com/duplicate'
    description: 'DAST created from Azure DevOps duplicate test'
    criticality: '30'