trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
- task: CreateDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetAddress: 'http://example.com/ohyeah'
    description: 'DAST created from Azure DevOps ohyeah'
    criticality: '30'

- task: ConfigureDASTTarget@1
  inputs:
    apiUrl: 'https://online.acunetix.com'
    targetId: '$(DASTTargetId)'
    limitCrawlerScope: true
    scanSpeed: 'medium'
    authenticationEnabled: true
    authUsername: 'test'
    authPassword: 'test'
    authUrl: 'http://example.com'

- task: StartDASTScan@1
  inputs:
    criticalThreshold: '2'
    highThreshold: '2'
    abortScanOnFindings: true
    targetId: '$(DASTTargetId)'
    scheduleDisable: true
    triggerable: true