trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:

- checkout: self

- task: netsparker-cloud@1
  inputs:
    apiConnection: 'Project Team A DAST Connection'
    scanTypes: '1'
    scanWebSites: '8380702c-ca3f-4213-e6f2-b325022a1cd0'
    buildFail: true
    severity: 'Critical,High'
    hasReport: true
    reportType: 'ScanDetail'
    isConfirmed: true
    ignoreFalsePositive: true